---
# yamllint disable rule:line-length
name: Build and tests

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    name: build on ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt-get -y install autotools-dev build-essential automake
      - name: autorecon
        run: autoreconf --install
      - name: configure
        run: ./configure
      - name: build
        run: make
      - name: run
        run: ./binrsync
